
package client;

import java.awt.Color;

import java.awt.event.ActionEvent;

import java.awt.event.ActionListener;
import java.awt.event.KeyListener;

import java.text.SimpleDateFormat;

import java.util.Date;

import javax.swing.BorderFactory;
import javax.swing.JComboBox;

/**
 *
 * @author ВМК
 */
public class NewJFrame extends javax.swing.JFrame implements ActionListener {
    String[] patternExample={"dd MMMM YYYY","dd.MM.yy","MM/dd/yy","h:mm a","yyyy.MMMMM.dd GGG hh:mm aaa","mm gg"};
    String currentParent;
   
    /** Creates new form NewJFrame */
    public NewJFrame() {
        initComponents();
        currentParent=patternExample[0];
        result.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(Color.black),BorderFactory.createEmptyBorder(5,5,5,5)));
    }
    public void reformat(){
        Date today = new Date();
        try{
            SimpleDateFormat formatter = new SimpleDateFormat(currentParent);
            String dateString = formatter.format(today);
            result.setForeground(Color.black);result.setText(dateString);
            }
        catch(IllegalArgumentException ex){result.setForeground(Color.red);
                                           result.setText("Ошибка"+ex.getMessage());
                                               };}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jComboBox1 = new JComboBox(patternExample);
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        result = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(5, 5));
        getContentPane().setLayout(null);

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(26, 117, 254, 63);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Выберите шаблон даты");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(26, 77, 254, 28);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setText("Текущая дата/время");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(26, 220, 254, 17);

        result.setBackground(new java.awt.Color(0, 0, 0));
        result.setText("result");
        getContentPane().add(result);
        result.setBounds(26, 249, 238, 74);

        pack();
    }//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
     
        JComboBox cb=(JComboBox)evt.getSource();
                            String newSelection = (String) cb.getSelectedItem();
                                                                 currentParent = newSelection;
                                                                 reformat();
 
 
 
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel result;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent actionEvent) {
        // TODO Implement this method
    }
}
